### PR TITLE
Streaming output cli

### PR DESCRIPTION
**Pull request by joranvar**
Hi!

My Python skills are probably not very refined, but I took a shot at adding a more asynchronous or streaming output mechanism. This also affects the cli feature, you might like to pick/merge some stuff, if it's useful to you :)

### CODE REVIEW

**Comment by jakobadam** [comment]
Cool. It would be great if the outputs are streamed. I have tried successfully with PING, getting replies streamed back:

```shell
$ winrm -l Administrator -i cmd -p V@grant 192.168.121.166 'ping 127.0.0.1'

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

However, something is not working when using powershell:
```python
$ winrm -v -l Administrator -i ps -p V@grant 192.168.121.166 '1+1'
sequence item 0: expected string, file found
Traceback (most recent call last):
  File "/home/jakob/projects/pywinrm/winrm/cli.py", line 177, in main
    response = run(args.command, args.hostname, **kwargs)
  File "/home/jakob/projects/pywinrm/winrm/__init__.py", line 24, in run
    return session.run_ps(command, args, ostreams)
  File "/home/jakob/projects/pywinrm/winrm/__init__.py", line 64, in run_ps
    rs = self.run_cmd("powershell -encodedcommand %s" % (base64_script), ostreams)
  File "/home/jakob/projects/pywinrm/winrm/__init__.py", line 50, in run_cmd
    command_id = self.protocol.run_command(shell_id, command, args)
  File "/home/jakob/projects/pywinrm/winrm/protocol.py", line 268, in run_command
    cmd_line['rsp:Arguments'] = ' '.join(arguments)
TypeError: sequence item 0: expected string, file found
```

Due to a missing argument when calling run_cmd. 

In addition, I would skip passing the streams around as argument to to all the methods, and instead put stdin and stderr as instance variables on the Protocol object.

kind regards,
Jakob

**Comment by joranvar** [comment]
Thanks for pointing that bug out (I should have tested more throrougly)! And making the streams instance variables makes more sense, indeed.

**Comment by jakobadam** [comment]
Thanks

**Comment by joranvar** [comment]
My pleasure :+1:

**Pull request merged**
